name: Incremental build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get branch name and short sha
        id: branch_name_short_sha
        run: |
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.branch_name_short_sha.outputs.branch }}-${{ steps.branch_name_short_sha.outputs.sha }}
          path: build
